name: Manual Approval

on: 
 push:
   branches:
      - main

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
      - name: waiting for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Gowtham0045
          exclude_workflow_initiator: true
