name: testing-on-push

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    steps:
    
      - name: waiting for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: technokarthyk, gowtham0045
          exclude_workflow_initiator: false

      - name: Checkout Repository
        uses: actions/checkout@v2    
